FROM aequitas/http-api-resource@sha256:769fddc7cc2f0a1c35abb2f91432e8beecf83916c421420e6a6da9f8975464b6
FROM python:3.7-alpine@sha256:769fddc7cc2f0a1c35abb2f91432e8beecf83916c421420e6a6da9f8975464b6
COPY --from=0 . .
RUN pip install --no-cache-dir -r requirements.txt
COPY --from=0 /opt/resource/ /opt/resource/
COPY --from=0 /opt/resource-tests/ /opt/resource-tests/
RUN /opt/resource-tests/test.sh
